import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { ArrowRight, Code2, ChevronDown, Globe2, GraduationCap, Menu, Network, Play, Search, Shield, Sparkles, X } from "lucide-react";

const pathways = [
  { icon: Shield, accent: "lime", kicker: "04 YEARS · 240 ECTS", title: "Cybersecurity", description: "From first principles to incident response. Build the judgment, technical depth and evidence practice that real security teams need.", courses: "12 courses · 8 labs" },
  { icon: Globe2, accent: "cyan", kicker: "LANGUAGES · GLOBAL", title: "Languages & culture", description: "Learn the language of the teams you want to join. Practice communication, technical vocabulary and cross-cultural collaboration.", courses: "6 languages · live practice" },
  { icon: Code2, accent: "coral", kicker: "FULL STACK · PROJECT BASED", title: "Full-stack development", description: "Design, ship and defend production-grade applications with a curriculum built around real systems, not toy exercises.", courses: "10 courses · 14 projects" },
];
const courses = [
  { code: "CY-101", title: "Cybersecurity Fundamentals", meta: "8 weeks · Beginner", color: "lime", icon: Shield, progress: 68 },
  { code: "WEB-201", title: "Web Application Security", meta: "10 weeks · Intermediate", color: "cyan", icon: Code2, progress: 42 },
  { code: "SOC-301", title: "Detection Engineering", meta: "12 weeks · Advanced", color: "violet", icon: Network, progress: 0 },
];
function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); }
function tone(accent: string) { return accent === "lime" ? "bg-[#b8f36b]/15 text-[#b8f36b]" : accent === "cyan" ? "bg-[#49dce8]/15 text-[#49dce8]" : "bg-[#ff8377]/15 text-[#ff8377]"; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [query, setQuery] = useState("");
  const discover = () => query.trim() ? (toast("Explorando el catálogo", { description: `Buscando “${query.trim()}” en Secure T.` }), setQuery("")) : scrollTo("programs");
  return <div className="min-h-screen overflow-hidden bg-[#071016] text-[#f3f7f3]">
    <div className="pointer-events-none fixed inset-0 -z-0 opacity-60 [background-image:linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] [background-size:72px_72px]" />
    <div className="pointer-events-none absolute left-[-10rem] top-[-10rem] h-[34rem] w-[34rem] rounded-full bg-[#b8f36b]/10 blur-[120px]" />
    <div className="pointer-events-none absolute right-[-12rem] top-[24rem] h-[30rem] w-[30rem] rounded-full bg-[#49dce8]/10 blur-[120px]" />
    <header className="relative z-20 border-b border-white/10 bg-[#071016]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
      <Link href="/" className="flex items-center gap-3" onClick={() => setMenuOpen(false)}><div className="grid size-9 place-items-center rounded-xl bg-[#b8f36b] text-[#071016] shadow-[0_0_28px_rgba(184,243,107,.2)]"><Shield className="size-5" strokeWidth={2.5} /></div><div><div className="font-display text-lg font-bold tracking-[-.04em]">secure<span className="text-[#b8f36b]">T</span></div><div className="eyebrow !text-[8px] !tracking-[.28em]">academy of applied security</div></div></Link>
      <nav className="hidden items-center gap-8 text-sm text-white/65 lg:flex"><button onClick={() => scrollTo("programs")} className="transition hover:text-white">Programs</button><button onClick={() => scrollTo("method")} className="transition hover:text-white">How it works</button><button onClick={() => scrollTo("community")} className="transition hover:text-white">Community</button></nav>
      <div className="hidden items-center gap-3 lg:flex"><Link href="/record" className="rounded-xl px-4 py-2 text-sm font-semibold text-white/70 transition hover:bg-white/5 hover:text-white">Student portal</Link><button onClick={() => toast("Admisiones abiertas", { description: "La solicitud de acceso estará disponible en la siguiente versión." })} className="rounded-xl bg-[#b8f36b] px-4 py-2 text-sm font-bold text-[#071016] transition hover:bg-[#d0ff9a] active:scale-[.98]">Apply now <ArrowRight className="ml-1 inline size-4" /></button></div>
      <button aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)} className="grid size-10 place-items-center rounded-xl border border-white/10 lg:hidden">{menuOpen ? <X /> : <Menu />}</button>
    </div>{menuOpen && <div className="border-t border-white/10 px-5 py-5 lg:hidden"><div className="grid gap-4 text-sm"><button onClick={() => { scrollTo("programs"); setMenuOpen(false); }} className="text-left text-white/75">Programs</button><button onClick={() => { scrollTo("method"); setMenuOpen(false); }} className="text-left text-white/75">How it works</button><Link href="/record" className="text-white/75">Student portal</Link><button onClick={() => toast("Admisiones abiertas", { description: "La solicitud de acceso estará disponible en la siguiente versión." })} className="rounded-xl bg-[#b8f36b] px-4 py-3 text-left font-bold text-[#071016]">Apply now</button></div></div>}</header>
    <main className="relative z-10">
      <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-16 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#b8f36b]/25 bg-[#b8f36b]/10 px-3 py-2 text-[11px] font-semibold tracking-[.13em] text-[#caff91]"><span className="size-1.5 rounded-full bg-[#b8f36b] shadow-[0_0_10px_#b8f36b]" /> COHORT 01 · APPLICATIONS OPEN</div><h1 className="max-w-3xl font-display text-5xl font-bold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-[6.25rem]">Learn to <span className="text-[#b8f36b]">secure</span><br />what matters.</h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-white/58">A modern university for cybersecurity, languages and full-stack development. Practice on real systems. Think in evidence. Build a career with signal.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={() => scrollTo("programs")} className="rounded-xl bg-[#b8f36b] px-5 py-3.5 text-sm font-bold text-[#071016] transition hover:bg-[#d0ff9a] active:scale-[.98]">Explore programs <ArrowRight className="ml-2 inline size-4" /></button><Link href="/record" className="rounded-xl border border-white/15 px-5 py-3.5 text-center text-sm font-semibold text-white/80 transition hover:border-white/30 hover:bg-white/5">Open student portal</Link></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-4 text-xs text-white/45"><span><strong className="font-mono text-white">01</strong> university mindset</span><span><strong className="font-mono text-white">02</strong> evidence-led labs</span><span><strong className="font-mono text-white">03</strong> human + AI support</span></div></div>
        <div className="relative mx-auto w-full max-w-[30rem] lg:justify-self-end"><div className="absolute -inset-5 rounded-[2rem] border border-[#b8f36b]/10" /><div className="relative overflow-hidden rounded-[1.75rem] border border-white/15 bg-[#101d24] p-5 shadow-[0_25px_80px_rgba(0,0,0,.35)] sm:p-7"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="eyebrow !text-[#b8f36b]">your learning cockpit</p><h2 className="mt-2 font-display text-xl font-bold">Good morning, Alex.</h2></div><div className="grid size-10 place-items-center rounded-full bg-[#b8f36b]/15 text-sm font-bold text-[#b8f36b]">AB</div></div><div className="mt-6 rounded-2xl border border-[#b8f36b]/25 bg-[#b8f36b]/[.07] p-5"><div className="flex items-start justify-between"><div><span className="rounded-full bg-[#b8f36b] px-2 py-1 text-[9px] font-black tracking-widest text-[#071016]">CONTINUE LEARNING</span><h3 className="mt-4 font-display text-lg font-bold">Threat model a public API</h3><p className="mt-1 text-xs text-white/45">Web Application Security · Module 03</p></div><Play className="mt-1 size-5 fill-[#b8f36b] text-[#b8f36b]" /></div><div className="mt-5 flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-white/10"><div className="h-full w-[68%] rounded-full bg-[#b8f36b]" /></div><span className="font-mono text-[11px] text-[#b8f36b]">68%</span></div></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><p className="font-mono text-2xl text-[#49dce8]">04</p><p className="mt-1 text-[11px] text-white/40">labs completed</p></div><div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><p className="font-mono text-2xl text-[#ff8377]">12h</p><p className="mt-1 text-[11px] text-white/40">this month</p></div></div><div className="mt-5 flex items-center gap-3 border-t border-white/10 pt-5"><div className="grid size-8 place-items-center rounded-lg bg-[#49dce8]/15 text-[#49dce8]"><Sparkles className="size-4" /></div><p className="text-xs leading-relaxed text-white/55"><strong className="text-white">Astra, your mentor</strong><br />Your next best action is ready.</p><ChevronDown className="ml-auto size-4 rotate-[-90deg] text-white/35" /></div></div></div>
      </section>
      <section id="programs" className="border-y border-white/10 bg-[#0b171d]/80 py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="eyebrow !text-[#b8f36b]">Choose your direction</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold tracking-[-.05em] sm:text-5xl">Three disciplines.<br /><span className="text-white/45">One connected campus.</span></h2></div><p className="max-w-sm text-sm leading-relaxed text-white/48">Start where you are. Stack skills across disciplines. Graduate with a body of work you can defend.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{pathways.map(({ icon: Icon, accent, kicker, title, description, courses: courseMeta }) => <button key={title} onClick={() => toast(title, { description: "Esta ruta académica se habilitará al completar tu perfil." })} className="group rounded-2xl border border-white/10 bg-[#101d24] p-6 text-left transition duration-200 hover:-translate-y-1 hover:border-white/25 hover:bg-[#13242c]"><div className={`grid size-11 place-items-center rounded-xl ${tone(accent)}`}><Icon className="size-5" /></div><p className="mt-8 text-[10px] font-mono tracking-[.18em] text-white/35">{kicker}</p><h3 className="mt-3 font-display text-2xl font-bold">{title}</h3><p className="mt-3 min-h-[72px] text-sm leading-relaxed text-white/48">{description}</p><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-4 text-xs text-white/40"><span>{courseMeta}</span><ArrowRight className="size-4 text-white/30 transition group-hover:translate-x-1 group-hover:text-white" /></div></button>)}</div></div></section>
      <section id="method" className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28"><div><p className="eyebrow !text-[#49dce8]">The secure T method</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.05em] sm:text-5xl">Not content.<br /><span className="text-[#49dce8]">Capability.</span></h2><p className="mt-6 max-w-md text-sm leading-relaxed text-white/50">Our learning model is designed around the work itself: understand the system, practice the decision, explain the evidence.</p><button onClick={() => toast("Method guide", { description: "The academic guide will be available soon." })} className="mt-8 text-sm font-bold text-[#b8f36b]">Read the academic guide <ArrowRight className="ml-1 inline size-4" /></button></div><div className="grid gap-3 sm:grid-cols-2">{[["01 / BUILD", "Learn the mental model", "Short lessons, clear language and a curriculum that connects theory to systems.", "text-[#b8f36b]"], ["02 / BREAK", "Practice in safe labs", "Work on isolated scenarios where curiosity is encouraged and mistakes are recoverable.", "text-[#49dce8]"], ["03 / PROVE", "Submit your evidence", "Build a record of decisions, artifacts and reflections—not just a percentage.", "text-[#ff8377]"], ["04 / GROW", "Get human feedback", "Mentors and peers help you calibrate your thinking. AI recommends; people stay accountable.", "text-[#bda2ff]"]].map(([number, title, text, color], i) => <div key={number} className={`rounded-2xl border border-white/10 bg-white/[.035] p-6 ${i % 2 ? "sm:translate-y-8" : ""}`}><span className={`font-mono text-sm ${color}`}>{number}</span><h3 className="mt-12 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-white/45">{text}</p></div>)}</div></section>
      <section className="border-t border-white/10 py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow !text-[#b8f36b]">Explore the catalogue</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.05em]">Courses with a point of view.</h2></div><div className="flex w-full max-w-xs items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2"><Search className="size-4 text-white/35" /><input aria-label="Search courses" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && discover()} placeholder="Search courses" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/30" /><button onClick={discover} className="text-xs font-bold text-[#b8f36b]">Go</button></div></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{courses.map(({ code, title, meta, color, icon: Icon, progress }) => <Link key={code} href="/record" className="group rounded-2xl border border-white/10 bg-[#101d24] p-5 transition hover:-translate-y-1 hover:border-white/25"><div className="flex items-center justify-between"><div className={`grid size-10 place-items-center rounded-xl ${tone(color)}`}><Icon className="size-5" /></div><span className="font-mono text-[10px] text-white/35">{code}</span></div><h3 className="mt-8 font-display text-xl font-bold">{title}</h3><p className="mt-2 text-xs text-white/42">{meta}</p><div className="mt-6 flex items-center gap-3"><div className="h-1 flex-1 rounded-full bg-white/10"><div className={`h-full rounded-full ${color === "lime" ? "bg-[#b8f36b]" : color === "cyan" ? "bg-[#49dce8]" : "bg-[#bda2ff]"}`} style={{ width: `${progress}%` }} /></div><span className="text-[10px] text-white/35">{progress ? `${progress}%` : "Start"}</span></div></Link>)}</div></div></section>
      <section id="community" className="mx-5 mb-20 overflow-hidden rounded-[1.75rem] border border-[#b8f36b]/20 bg-[#b8f36b] text-[#071016] lg:mx-auto lg:max-w-7xl"><div className="relative grid gap-10 px-7 py-12 sm:px-12 lg:grid-cols-[1fr_auto] lg:items-center lg:px-16 lg:py-14"><div className="absolute right-[-5rem] top-[-8rem] size-80 rounded-full border-[1.5rem] border-[#071016]/[.06]" /><div><p className="font-mono text-[10px] font-bold tracking-[.2em] text-[#071016]/60">YOUR NEXT CHAPTER STARTS HERE</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-bold tracking-[-.05em] sm:text-5xl">Build a future worth defending.</h2><p className="mt-4 max-w-xl text-sm leading-relaxed text-[#071016]/65">Join a cohort of curious people learning to make technology more trustworthy.</p></div><button onClick={() => toast("Welcome to Secure T", { description: "Create your learner profile to start exploring the campus." })} className="relative flex items-center justify-center gap-2 rounded-xl bg-[#071016] px-5 py-3.5 text-sm font-bold text-white transition hover:bg-[#13242c]">Create your profile <ArrowRight className="size-4" /></button></div></section>
    </main>
    <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-8 text-xs text-white/35 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="flex items-center gap-2 text-white/60"><GraduationCap className="size-4 text-[#b8f36b]" /> secureT academy</div><div className="flex gap-5"><span>Learning in public.</span><span>© 2026 secureT</span></div><Link href="/settings" className="transition hover:text-white">Privacy & settings</Link></div></footer>
  </div>;
}
