// AUTO-GENERATED by scripts/generate-platform.py — do not edit by hand.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

export interface CatalogLesson { id: string; title: string; type: string; minutes: number; objective: string; }
export interface CatalogModule { id: string; title: string; source: string; lessons: CatalogLesson[]; }
export interface CatalogCourse {
  code: string; track: string; title: string; subtitle: string; level: string;
  weeks: number; hoursPerWeek: number; prerequisites: string[]; skills: string[];
  credential: string; modules: CatalogModule[];
}
export interface CatalogTrack { id: string; title: string; level: string; description: string; courses: string[]; }
export interface Catalog {
  schema: string; generatedAt: string;
  institution: Record<string, unknown>;
  tracks: CatalogTrack[]; courses: CatalogCourse[];
  stats: { tracks: number; courses: number; modules: number; lessons: number };
}

const here = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(join(here, "..", "..", "education", "catalog.json"), "utf-8"));

export const CATALOG: Catalog = {
  schema: raw.schema,
  generatedAt: raw.generated_at,
  institution: raw.institution,
  tracks: raw.tracks,
  courses: raw.courses,
  stats: raw.stats,
};

export function getCourse(code: string): CatalogCourse | undefined {
  return CATALOG.courses.find((c) => c.code === code);
}

export function getTrack(id: string): CatalogTrack | undefined {
  return CATALOG.tracks.find((t) => t.id === id);
}
